# -*- coding: utf-8 -*-
"""bones_practiques

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K4IWHQ0W8jXAzS1FrLLrfxrdXTGrMD7e
"""

"""
Divisió entera entre dos nombres enters.

Institut: Institut Icària
Programació - 1r Batxillerat - Curs 2025-2026

Author: Héctor Robledo Saavedra
Email: hrobledo@gmail.com
Date: 29/10/2025
"""

dividend = int(input("Introdueix el dividend: "))
divisor = int(input("Introdueix el divisor: "))
divisor == 0:
print("Error: no es pot dividir entre zero.")
quocient = dividend // divisor
residu = dividend % divisor
print("\n===== RESULTATS =====")
print(f"Divisió: {dividend} ÷ {divisor}")
print(f"Quocient: {quocient}")
print(f"Residu: {residu}")
print("=====================")