# -*- coding: utf-8 -*-
"""bones_practiques

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K4IWHQ0W8jXAzS1FrLLrfxrdXTGrMD7e
"""

#!/usr/bin/env python3
# Programa: Divisió entera
# Autor: Héctor Robledo Saavedra
# Descripció: Calcula el quocient i el residu de la divisió entre dos nombres enters.


dividend = int(input("Introdueix el dividend: "))
divisor = int(input("Introdueix el divisor: "))


if divisor == 0:
    print("Error: no es pot dividir entre zero.")
else:
    quocient = dividend // divisor
    residu = dividend % divisor
    print("Divisió:", str(dividend) + "/" + str(divisor))
    print("Quocient:", quocient)
    print("Residu:", residu)